name: publish
on: [ workflow_dispatch ]
jobs:
  publish:
    name: build and publish image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          pass: true
          tags: indiciez/nestjs-app:latest